apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: blackbird-python 
  janus-idp.io/tekton: blackbird-python
  backstage.io/kubernetes-id: blackbird-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: blackbird-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  